import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionClientProvider from "./components/SessionClientProvider"; // <-- Import the client provider
import { CartProvider } from "@/app/components/CartContext"; // <-- Import the CartProvider
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionClientProvider>
          <CartProvider>{children}</CartProvider>
        </SessionClientProvider>
      </body>
    </html>
  );
}
